// <auto-generated />
using System;
using HomeQI.Adream.Identity.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HomeQI.ADream.Identity.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(IdentityDbContext))]
    [Migration("20180720060534_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HomeQI.Adream.Identity.IdentityPermission", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Action")
                        .IsRequired();

                    b.Property<string>("AreaName")
                        .IsRequired();

                    b.Property<string>("Controller")
                        .IsRequired();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("CretaedUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("EditeUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("EditedTime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<bool>("IsAllowAnonymous");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("IsEnable");

                    b.Property<int>("Level");

                    b.Property<string>("Params")
                        .IsRequired();

                    b.Property<int>("ShowSort");

                    b.HasKey("Id");

                    b.HasIndex("Action")
                        .HasName("ActionIndex");

                    b.HasIndex("AreaName")
                        .HasName("AreaNameIndex");

                    b.HasIndex("Controller")
                        .HasName("ControllerIndex");

                    b.HasIndex("Params")
                        .HasName("ParamsIndex");

                    b.ToTable("Permissions");
                });

            modelBuilder.Entity("HomeQI.Adream.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("CretaedUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("EditeUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("EditedTime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .HasName("RoleNameIndex");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("HomeQI.Adream.Identity.IdentityRoleClaim", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType")
                        .IsRequired();

                    b.Property<string>("ClaimValue")
                        .IsRequired();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("CretaedUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("EditeUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("EditedTime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("RoleId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ClaimType")
                        .HasName("ClaimTypeIndex");

                    b.HasIndex("ClaimValue")
                        .HasName("ClaimValueIndex");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims");
                });

            modelBuilder.Entity("HomeQI.Adream.Identity.IdentityUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .IsRequired();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("CretaedUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("EditeUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("EditedTime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("IsDeleted");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTime>("LockoutEnd");

                    b.Property<string>("NormalizedEmail")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("NormalizedUserName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.Property<string>("PasswordHash")
                        .IsRequired();

                    b.Property<string>("PhoneNumber")
                        .IsRequired();

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("SecurityStamp")
                        .IsRequired();

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256);

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .HasName("EmailIndex");

                    b.HasIndex("NormalizedEmail")
                        .HasName("NormalizedEmailIndex");

                    b.HasIndex("PhoneNumber")
                        .HasName("PhoneNumberIndex");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeQI.Adream.Identity.IdentityUserClaim", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("ClaimType")
                        .IsRequired();

                    b.Property<string>("ClaimValue")
                        .IsRequired();

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("CretaedUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("EditeUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("EditedTime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("Id");

                    b.HasIndex("ClaimType")
                        .HasName("ClaimTypeIndex");

                    b.HasIndex("ClaimValue")
                        .HasName("ClaimValueIndex");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims");
                });

            modelBuilder.Entity("HomeQI.Adream.Identity.IdentityUserLogin", b =>
                {
                    b.Property<string>("LoginProvider");

                    b.Property<string>("ProviderKey");

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("CretaedUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("EditeUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("EditedTime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Id")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("ProviderDisplayName")
                        .IsRequired();

                    b.Property<string>("UserId")
                        .IsRequired();

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasAlternateKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins");
                });

            modelBuilder.Entity("HomeQI.Adream.Identity.IdentityUserRole", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("RoleId");

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("CretaedUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("EditeUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("EditedTime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Id")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.HasKey("UserId", "RoleId");

                    b.HasAlternateKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles");
                });

            modelBuilder.Entity("HomeQI.Adream.Identity.IdentityUserToken", b =>
                {
                    b.Property<string>("UserId");

                    b.Property<string>("LoginProvider");

                    b.Property<string>("Name");

                    b.Property<DateTime>("CreatedTime");

                    b.Property<string>("CretaedUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<string>("Description")
                        .IsRequired();

                    b.Property<string>("EditeUser")
                        .IsRequired()
                        .HasMaxLength(50);

                    b.Property<DateTime>("EditedTime")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate();

                    b.Property<string>("Id")
                        .IsRequired();

                    b.Property<bool>("IsDeleted");

                    b.Property<string>("Value")
                        .IsRequired();

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.HasAlternateKey("Id");

                    b.ToTable("UserTokens");
                });

            modelBuilder.Entity("HomeQI.Adream.Identity.IdentityRoleClaim", b =>
                {
                    b.HasOne("HomeQI.Adream.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HomeQI.Adream.Identity.IdentityUserClaim", b =>
                {
                    b.HasOne("HomeQI.Adream.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HomeQI.Adream.Identity.IdentityUserLogin", b =>
                {
                    b.HasOne("HomeQI.Adream.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HomeQI.Adream.Identity.IdentityUserRole", b =>
                {
                    b.HasOne("HomeQI.Adream.Identity.IdentityRole")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("HomeQI.Adream.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HomeQI.Adream.Identity.IdentityUserToken", b =>
                {
                    b.HasOne("HomeQI.Adream.Identity.IdentityUser")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
